### ISSUE TITLE
Firefox clipboard upload issue?

### ISSUE THREAD

**Issue by 3k2** [v0l/void.cat#17]
In firefox if I use clipboard upload feature on the first time it works fine but usually second time nothing happens even if I use everytime different picture. After refreshing site it works again for first picture then second wont work anymore.

It could be issue in firefox or site not sure. But in chromium/chrome it works everytime.

**Comment by v0l** [comment]
If you click the header where it says "void.cat" it should work again, when you click on the background area you are essentially pasting onto the background, this area doesn't have the paste event scripted in.

To resolve this simply click on the header part again so that you are pasting the content there. This is unfortunately due to how the center page is rendered with polymer.

**Comment by 3k2** [comment]
Seems to be working thx.

Are there any plans to upgrade the server bandwidth? seems to have pretty high load constantly now?

**Comment by v0l** [comment]
Cant upgrade it, would need to switch to a different provider or something.. more $$$
